// <auto-generated />
using System;
using Dungeon.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dungeon.EntityFramework.Migrations
{
    [DbContext(typeof(DungeonContext))]
    partial class DungeonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dungeon.Logic.Model.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("Dungeon.Logic.Model.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryId"));

                    b.Property<int?>("EntranceRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StoryId");

                    b.HasIndex("EntranceRoomId");

                    b.ToTable("Story", (string)null);
                });

            modelBuilder.Entity("Dungeon.Logic.Model.Room", b =>
                {
                    b.OwnsMany("Dungeon.Logic.Model.RoomExit", "Exits", b1 =>
                        {
                            b1.Property<int>("ExitRoomRoomId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Keyword")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("ExitRoomRoomId", "Id");

                            b1.ToTable("RoomExit");

                            b1.WithOwner("ExitRoom")
                                .HasForeignKey("ExitRoomRoomId");

                            b1.Navigation("ExitRoom");
                        });

                    b.Navigation("Exits");
                });

            modelBuilder.Entity("Dungeon.Logic.Model.Story", b =>
                {
                    b.HasOne("Dungeon.Logic.Model.Room", "Entrance")
                        .WithMany()
                        .HasForeignKey("EntranceRoomId");

                    b.Navigation("Entrance");
                });
#pragma warning restore 612, 618
        }
    }
}
